<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Review;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends EntityRepository implements ReviewRepositoryInterface
{
    private $directory;

    public function save(Review $review, bool $flush = true): Review
    {
        if ($review->getFile() !== null) {
            $this->upload($review);
        }

        $this->getEntityManager()->persist($review);

        if ($flush) {
            $this->getEntityManager()->flush();
        }

        return $review;
    }

    public function setDirectory($directory)
    {
        $this->directory = $directory;
    }

    private function upload(Review $review)
    {
        $file = $review->getFile();

        $filename = md5(uniqid()).'.'.$file->guessExtension();

        $file->move(
            $this->directory,
            $filename
        );

        $review->setFilename($filename);
    }
}
