<?php
/**
 * Created by PhpStorm.
 * User: fintara
 * Date: 24/01/2017
 * Time: 14:22
 */
namespace AppBundle\Repository;
use AppBundle\Entity\Review;


/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
interface ReviewRepositoryInterface
{
    public function save(Review $review, bool $flush = true): Review;
    public function setDirectory($directory);
}