<?php

namespace AppBundle\Repository;

/**
 * ThesisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThesisRepository extends \Doctrine\ORM\EntityRepository
{
}
