# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db:
            id: user.provider

    encoders:
        AppBundle\Entity\User: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true

#            form_login:
#                check_path: app_login_post
#                login_path: app_login_get
                #csrf_provider: security.csrf.token_manager

            guard:
                authenticators:
                    - form_authenticator

            logout:
                path: app_logout
                target: app_home_get
