# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  ##################################
  ## USER
  user.provider:
    class: AppBundle\Security\User\MultiUserProvider
    arguments: [ "@user.repository" ]

  user.factory:
    class: AppBundle\Factory\UserFactory

  user.normalizer:
    class: AppBundle\Serializer\Normalizer\UserNormalizer
    tags:
      - { name: serializer.normalizer }

  user.repository:
    class: AppBundle\Repository\UserRepository
    factory: ["@doctrine", getRepository]
    arguments: [ "AppBundle:User" ]

  user.service:
    class: AppBundle\Services\UserService
    arguments:
      - "@user.repository"
      - "@user.factory"
      - "@security.password_encoder"

  #################################
  ## TOPICS
  topic.normalizer:
    class: AppBundle\Serializer\Normalizer\TopicNormalizer
    tags:
      - { name: serializer.normalizer }

  topic.repository:
    class: AppBundle\Repository\TopicRepository
    factory: ["@doctrine", getRepository]
    arguments: [ "AppBundle:Topic" ]

  topic.service:
    class: AppBundle\Services\TopicService
    arguments:
      - "@topic.repository"
      - "@reservation.repository"

  ##################################
  ## RESERVATIONS
  reservation.repository:
    class: AppBundle\Repository\ReservationRepository
    factory: ["@doctrine", getRepository]
    arguments: [ "AppBundle:Reservation" ]
  ##################################
  ## MISC
  form_authenticator:
    class: AppBundle\Security\FormAuthenticator
    arguments:
      - "@security.password_encoder"
      - "@router"
