# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  user.provider:
    class: AppBundle\Security\User\MultiUserProvider
    arguments: [ "@user.repository" ]

  user.factory:
    class: AppBundle\Factory\UserFactory

  user.repository:
    class: AppBundle\Repository\UserRepository
    factory: ["@doctrine", getRepository]
    arguments: [ "AppBundle:User" ]

  user.service:
    class: AppBundle\Services\UserService
    arguments:
      - "@user.repository"
      - "@user.factory"
      - "@security.password_encoder"

  form_authenticator:
    class: AppBundle\Security\FormAuthenticator
    arguments:
      - "@security.password_encoder"
      - "@router"
