app_home_get:
  path: /
  defaults: { _controller: AppBundle:Default:index }
  methods: [GET]

app_login_get:
  path: /login
  defaults: { _controller: AppBundle:Auth:getLogin }
  methods: [GET]

app_login_post:
  path: /login
  defaults: { _controller: AppBundle:Auth:postLogin }
  methods: [POST]

app_logout:
  path: /logout
  defaults: { _controller: AppBundle:Default:index }
  methods: [GET]

app_topics_get:
  path: /topics
  defaults: { _controller: AppBundle:Topics:getTopics }
  methods: [GET]

app_topics_ajax:
  path: /topics/ajax
  defaults: { _controller: AppBundle:Topics:ajaxGetTopics }
  methods: [GET]

app_topics_reserve:
  path: /topics/{id}/reserve
  defaults: { _controller: AppBundle:Topics:ajaxReserveTopic }
  methods: [POST]
#  condition: "request.isXmlHttpRequest()"

app_theses_choose_reviewers_get:
  path: /theses/reviewers
  defaults: { _controller: AppBundle:Thesis:getChooseReviewers }
  methods: [GET]

app_theses_choose_reviewers_ajax:
  path: /theses/reviewers/ajax
  defaults: { _controller: AppBundle:Thesis:ajaxGetChooseReviewers }
  methods: [GET]

#app_thesis_submit_review:
#  path: /thesis/{thesis_id}/submit
#  defaults: { _controller: AppBundle:Default:submitReview }
#  methods: [GET, POST]

