app_home_get:
  path: /
  defaults: { _controller: AppBundle:Default:index }
  methods: [GET]

app_login_get:
  path: /login
  defaults: { _controller: AppBundle:Auth:getLogin }
  methods: [GET]

app_login_post:
  path: /login
  defaults: { _controller: AppBundle:Auth:postLogin }
  methods: [POST]

app_logout:
  path: /logout
  defaults: { _controller: AppBundle:Default:index }
  methods: [GET]

app_topics:
  prefix: /topics
  resource: topics.yml

app_theses:
  prefix: /theses
  resource: theses.yml

#app_thesis_submit_review:
#  path: /thesis/{thesis_id}/submit
#  defaults: { _controller: AppBundle:Default:submitReview }
#  methods: [GET, POST]

